### ISSUE TITLE
Error in the Analysis of Glass as a Refractory Material

### ISSUE THREAD

**Issue by VinayR-GitHub** [s1050613/4d-refraction#2]
To @s1050613,

I would like to pose an oversight that may have occurred during the development of this process, which I deem to be of great importance. Note that, in 3-dimensional space, glass is a lattice (giant network covalent solid) of empirical formula approaching SiO2. This structure is, in particular, tetrahedral in nature. However, it is reasonable to believe that given a higher dimension, the lattice nature of glass may not be well-defined. A 3-sphere would be unlikely, or impossible, to form due to restrictions on the valency of the carbon atom. Therefore, I think that this resource should either be edited to reflect the difficulty posed by glass refraction, or that an explanation is provisioned for the decision of using glass as the material in question.

Thank you for your time.

**Comment by s1050613** [comment]
To @VinayR-GitHub,

I appreciate your concern you raised with the physical validity of this program. Note that this program does not consider the molecular structure of materials, as each material's physical properties only includes its colour, refractive index, and if it is fully reflective or not. In particular, the refractive index for materials can be found in main.html#179. Such refractive indices can be modified at any time to adjust results. In fact, the refractive index used for "glass" in this program is much higher than the actual refractive index of glass. Naming the main object in the 4D scene a "glass hypersphere" was only to indicate to less scientifically versed individuals how the refractive nature seen in the render is similar to that seen in glass and glass-based materials in the real world (whatever that is). If you would like the naming to be changed, please submit a pull request.

Thank you.
